"""问题2固定配置；复用已经验证的储能参数。"""
from datetime import date, timedelta

from ..question1.config import (
    PROJECT_ROOT, N_SLOTS, BLOCK_SIZE, TIME_STEP_HOURS, SOC_MIN_KWH,
    SOC_MAX_KWH, INITIAL_SOC_KWH, FINAL_SOC_KWH, ETA_CHARGE, ETA_DISCHARGE,
    BATTERY_ENERGY_MAX_PER_SLOT_KWH, EPS_THROUGHPUT, TOL, RESIDUAL_TOL,
)

PRICE_XLSX = PROJECT_ROOT / "data" / "附件1.xlsx"
ACTUAL_XLSX = PROJECT_ROOT / "data" / "附件2.xlsx"
RESULT_XLSX = PROJECT_ROOT / "target" / "附件5" / "result2.xlsx"
OUTPUT_DIR = PROJECT_ROOT / "target" / "question2"
HISTORY_WINDOW_DAYS = 31
EMERGENCY_PRICE_MULTIPLIER = 5.0
EMERGENCY_TOL = 1e-6
SCENARIO_METHOD = "raw_equal"
STORAGE_EXECUTION = "causal_mpc"
OFFICIAL_STRATEGY = "residual_weighted_causal"
MPC_REOPTIMIZE_SLOTS = 1
RECOURSE_EPS_THROUGHPUT = 1e-5
RECENCY_TAU_DAYS = 14.0
SAME_WEEKDAY_WEIGHT = 2.0
LOAD_SCENARIO_CORRECTION = "none"
WEEKDAY_LAG_WEIGHTS = (0.40, 0.30, 0.20, 0.10)
LOAD_TREND_SHORT_DAYS = 7
LOAD_TREND_LONG_DAYS = 28
LOAD_TREND_BETA = 1.0
LEVEL_SCALE_MIN = 0.85
LEVEL_SCALE_MAX = 1.15
LOAD_FORECAST_WEEKDAY_BLEND = 0.7
PV_FORECAST_WINDOW_DAYS = 7
START_DATE = date(2025, 2, 1)
END_DATE = date(2025, 12, 31)
ANNUAL_DATES = tuple(date(2025, 1, 1) + timedelta(days=i) for i in range(365))
OUTPUT_DATES = tuple(START_DATE + timedelta(days=i) for i in range((END_DATE - START_DATE).days + 1))
PAPER_DATES = (date(2025, 3, 20), date(2025, 6, 21), date(2025, 9, 23), date(2025, 12, 21))
