"""固定物理参数与相对于代码位置的路径。"""
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
INPUT_XLSX = PROJECT_ROOT / "data" / "附件1.xlsx"
RESULT_XLSX = PROJECT_ROOT / "target" / "附件5" / "result1.xlsx"
N_SLOTS = 144
BLOCK_SIZE = 24
TIME_STEP_HOURS = 1.0 / 6.0
BATTERY_CAPACITY_KWH = 12000.0
SOC_MIN_KWH = 1200.0
SOC_MAX_KWH = 10800.0
INITIAL_SOC_KWH = FINAL_SOC_KWH = 6000.0
BATTERY_POWER_MAX_KW = 5000.0
BATTERY_ENERGY_MAX_PER_SLOT_KWH = BATTERY_POWER_MAX_KW * TIME_STEP_HOURS
ETA_CHARGE = ETA_DISCHARGE = 0.9
EPS_THROUGHPUT = 1e-8
TOL = 1e-6
RESIDUAL_TOL = 1e-5
